# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_job', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 10, 23, 18, 7, 48, 949501), editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
