# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171023_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 18, 9, 18, 232000), editable=False),
        ),
    ]
